Fix combine_by_coords monotonic issue.
_combine_single_variable_hypercube check the indexes.is_monotonic_increasing or indexes.is_monotonic_decreasing
from the concatenated dataset.

But if the differante dataset combine have the same coordinate in one dim they is some duplication in the dims values.
So before check the indexes is monotonic we should drop the duplication.

eg:

dataset_1 :
- latitude : [1, 2, 3, 4, 5]
- longitude: [1, 2, 3, 4, 5]
- vals     : x

dataset_2 :
- latitude : [1, 2, 3, 4, 5]
- longitude: [6, 7, 8, 9, 10]
- values   : y

the combine_by_coords should return ->

4 x x x x x y y y y y
3 x x x x x y y y y y
2 x x x x x y y y y y
1 x x x x x y y y y y
  1 2 3 4 5 6 7 8 9 10

and not return

ValueError: Resulting object does not have monotonic global indexes along dimension longitude